-- From https://github.com/josean-dev/dev-environment-files and https://www.youtube.com/watch?v=vdn_pKJUda8
require("lobis.plugins-setup")
require("lobis.core.options")
require("lobis.core.keymaps")
require("lobis.core.colorscheme")
require("lobis.plugins.comment")
require("lobis.plugins.nvim-tree")
require("lobis.plugins.lualine")
require("lobis.plugins.telescope")
require("lobis.plugins.nvim-cmp")
require("lobis.plugins.lsp.mason")
require("lobis.plugins.lsp.lspsaga")
require("lobis.plugins.lsp.lspconfig")
require("lobis.plugins.lsp.null-ls")
require("lobis.plugins.autopairs")
require("lobis.plugins.treesitter")
require("lobis.plugins.gitsigns")
