name: Install dependencies and verify scripts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh:
    name: Install zsh and oh-my-zsh with plugins
    strategy:
      fail-fast: false
      matrix:
        image: ["ubuntu:latest", "archlinux:latest"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Install zsh and dependencies for Ubuntu
        if: matrix.image == 'ubuntu:latest'
        run: |
          apt-get update
          apt-get install -y zsh curl git tmux

      - name: Install zsh and dependencies for Arch
        if: matrix.image == 'archlinux:latest'
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm zsh curl git tmux

      - name: Copy dotfiles
        run: cp .* ~/

      - name: Install oh-my-zsh and plugins using script
        run: sh ./zsh/install.sh

      - name: Run tmux to trigger plugin manager installation (tpm)
        run: |
          tmux new-session -d -s trigger-install-session
          tmux kill-session -t trigger-install-session
          [ -d "~/.tmux/plugins/tpm" ] && [ -d "~/.tmux/plugins/tmux-themepack" ] && echo "tmux plugins OK" || exit 1
