name: Install dependencies and verify scripts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  zsh:
    name: Install zsh and oh-my-zsh with plugins
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v3

      - name: Install zsh and dependencies
        run: apt update
          apt install zsh curl git

      - name: Install oh-my-zsh and plugins using script
        run: sh ./zsh/install.sh
