name: Install dependencies and verify scripts

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  chezmoi:
    name: Install dotfiles and plugins with chezmoi script
    strategy:
      fail-fast: false
      matrix:
        image: ["ubuntu:latest", "archlinux:latest"]
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.image }}
    timeout-minutes: 20

    steps:
      - name: Install zsh and dependencies for Ubuntu
        if: matrix.image == 'ubuntu:latest'
        run: |
          apt-get update
          apt-get install -y zsh curl git rsync tmux

      - name: Install zsh and dependencies for Arch
        if: matrix.image == 'archlinux:latest'
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm zsh curl git rsync tmux

      - name: Run install script
        run: |
          sh -c "$(curl -fsSL https://raw.githubusercontent.com/lobis/dotfiles/main/zsh/install.sh)"

      - name: Check oh-my-zsh plugins
        run: |
          touch ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting/.test
          touch ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions/.test
          touch ~/.oh-my-zsh/custom/themes/powerlevel10k/.test

      - name: Check tmux plugings
        run: |
          touch ~/.tmux/plugins/tpm/.test
          touch ~/.tmux/plugins/tmux-themepack/.test
